/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dont_touch_alggagi_alggagijni */

#ifndef _Included_dont_touch_alggagi_alggagijni
#define _Included_dont_touch_alggagi_alggagijni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dont_touch_alggagi_alggagijni
 * Method:    jniLoadGameData
 * Signature: (FF)I
 */
JNIEXPORT jint JNICALL Java_dont_touch_alggagi_alggagijni_jniLoadGameData
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     dont_touch_alggagi_alggagijni
 * Method:    jniReceive
 * Signature: (IFFFF)I
 */
JNIEXPORT jint JNICALL Java_dont_touch_alggagi_alggagijni_jniReceive
  (JNIEnv *, jobject, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     dont_touch_alggagi_alggagijni
 * Method:    jniDoGame
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_dont_touch_alggagi_alggagijni_jniDoGame
  (JNIEnv *, jobject, jint);

/*
 * Class:     dont_touch_alggagi_alggagijni
 * Method:    jniGetX
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_dont_touch_alggagi_alggagijni_jniGetX
  (JNIEnv *, jobject, jint);

/*
 * Class:     dont_touch_alggagi_alggagijni
 * Method:    jniGetY
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_dont_touch_alggagi_alggagijni_jniGetY
  (JNIEnv *, jobject, jint);

/*
 * Class:     dont_touch_alggagi_alggagijni
 * Method:    jniGetAngle
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_dont_touch_alggagi_alggagijni_jniGetAngle
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
